# Generated by Django 5.2.4 on 2025-11-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
