# Generated by Django 5.2.4 on 2025-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_token_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='working_hours',
            field=models.CharField(default='09:00 AM - 05:00 PM', max_length=100),
        ),
    ]
