# Generated by Django 6.0.1 on 2026-01-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='working_hours',
            field=models.CharField(default='09:00 AM - 02:00 PM', max_length=100),
        ),
    ]
